import { afterEach, describe, expect, it } from "bun:test";
import { createApiKey, getRoblosecurity } from "./index.js";

const originalRoblosecurity = process.env.ROBLOSECURITY;

function startCloudAuthServer({ csrfToken, apiResponse, apiStatus = 200 }) {
  const requests = [];
  const server = Bun.serve({
    port: 0,
    async fetch(request) {
      requests.push({
        method: request.method,
        cookie: request.headers.get("cookie"),
        csrfToken: request.headers.get("x-csrf-token"),
        contentType: request.headers.get("content-type"),
        body: await request.text(),
      });

      if (requests.length === 1) {
        return new Response(null, {
          status: 403,
          headers: csrfToken ? { "x-csrf-token": csrfToken } : {},
        });
      }

      return new Response(JSON.stringify(apiResponse), {
        status: apiStatus,
        headers: { "content-type": "application/json" },
      });
    },
  });

  return {
    url: new URL("api-key", server.url).toString(),
    requests,
    stop: () => server.stop(),
  };
}

afterEach(() => {
  if (originalRoblosecurity === undefined) {
    delete process.env.ROBLOSECURITY;
  } else {
    process.env.ROBLOSECURITY = originalRoblosecurity;
  }
});

describe("package integration", () => {
  it("gets the ROBLOSECURITY cookie from the environment", () => {
    process.env.ROBLOSECURITY = "integration-cookie";

    expect(getRoblosecurity()).toBe("integration-cookie");
  });

  it("creates an API key through the complete CSRF and API flow", async () => {
    const server = startCloudAuthServer({
      csrfToken: "integration-csrf",
      apiResponse: {
        cloudAuthInfo: { id: "app-123", ownerId: 456 },
        apikeySecret: "api-secret",
      },
    });
    const scopes = [
      {
        scopeType: "universe",
        targetParts: ["universe-123"],
        operations: ["read"],
      },
    ];

    try {
      const context = await createApiKey({
        url: server.url,
        name: "integration-key",
        description: "Integration test key",
        isEnabled: false,
        allowedCidrs: ["127.0.0.1/32"],
        scopes,
        roblosecurity: "integration-cookie",
      });

      expect(context).toEqual({
        id: "app-123",
        userId: 456,
        apiKey: "api-secret",
        roblosecurity: "integration-cookie",
      });
      expect(server.requests).toHaveLength(2);
      expect(server.requests[0]).toMatchObject({
        method: "POST",
        cookie: ".ROBLOSECURITY=integration-cookie",
      });
      expect(server.requests[1]).toMatchObject({
        method: "POST",
        cookie: ".ROBLOSECURITY=integration-cookie",
        csrfToken: "integration-csrf",
        contentType: "application/json",
      });
      expect(JSON.parse(server.requests[1].body)).toEqual({
        cloudAuthUserConfiguredProperties: {
          name: "integration-key",
          description: "Integration test key",
          isEnabled: false,
          allowedCidrs: ["127.0.0.1/32"],
          scopes,
        },
      });
    } finally {
      await server.stop();
    }
  });

  it("applies the documented defaults when options are omitted", async () => {
    const server = startCloudAuthServer({
      csrfToken: "integration-csrf",
      apiResponse: {
        cloudAuthInfo: { id: "app-123", ownerId: 456 },
        apikeySecret: "api-secret",
      },
    });

    try {
      await createApiKey({
        roblosecurity: "integration-cookie",
        url: server.url,
      });

      const body = JSON.parse(server.requests[1].body);
      const properties = body.cloudAuthUserConfiguredProperties;

      expect(properties.name).toMatch(/^lmir_[a-z0-9]{10}$/);
      expect(properties.description).toBe("Generated by let-me-into-roblox");
      expect(properties.isEnabled).toBe(true);
      expect(properties.allowedCidrs).toEqual(["0.0.0.0/0"]);
      expect(properties.scopes.length).toBeGreaterThan(0);
    } finally {
      await server.stop();
    }
  });

  it("rejects when the CSRF token cannot be retrieved", async () => {
    const server = startCloudAuthServer({
      apiResponse: {},
    });

    try {
      await expect(
        createApiKey({
          roblosecurity: "invalid-cookie",
          url: server.url,
        }),
      ).rejects.toThrow("Failed to get CSRF token");
      expect(server.requests).toHaveLength(1);
    } finally {
      await server.stop();
    }
  });

  it("rejects with the API response when key creation fails", async () => {
    const server = startCloudAuthServer({
      csrfToken: "integration-csrf",
      apiResponse: { message: "invalid request" },
      apiStatus: 400,
    });

    try {
      await expect(
        createApiKey({
          roblosecurity: "integration-cookie",
          url: server.url,
        }),
      ).rejects.toThrow("Failed to create API key: 400");
      expect(server.requests).toHaveLength(2);
    } finally {
      await server.stop();
    }
  });
});
