/**
 * @typedef {object} ApiContext
 * @property {string} id The ID of the authenticated user or application.
 * @property {number} userId The numeric ID of the authenticated user.
 * @property {string} apiKey The API key used for Cloud API requests.
 * @property {string} roblosecurity The ROBLOSECURITY cookie for the session.
 */

/**
 * Gets a CSRF token using the provided ROBLOSECURITY cookie.
 *
 * Will log an error and return undefined if the request fails for any reason, such as an invalid cookie or network issues.
 *
 * @param {object} options
 * @param {string} options.url The URL to request the CSRF token from.
 * @param {string} options.roblosecurity The user's ROBLOSECURITY cookie value.
 * @returns {Promise<string>} A promise resolving to the CSRF token string, or undefined if the request failed.
 */
export async function getRobloxCsrfToken({ url, roblosecurity }) {
  const res = await fetch(url, {
    method: "POST",
    headers: {
      Cookie: `.ROBLOSECURITY=${roblosecurity}`,
    },
  });
  return res.headers.get("x-csrf-token");
}

/**
 * Creates a new Open Cloud API Key on Roblox.
 * This does not store the API context anywhere; it's the caller's responsibility to save it if needed.
 *
 * @param {object} options
 * @param {string} options.roblosecurity The user's ROBLOSECURITY cookie value.
 * @param {string?} options.url The URL to create the API key at. Defaults to "https://apis.roblox.com/cloud-authentication/v1/apiKey".
 * @param {string?} options.name The name for the new API key.
 * @param {string?} options.description An optional description for the new API key.
 * @param {boolean?} options.isEnabled Whether the new API key should be enabled. Defaults to true.
 * @param {string[]?} options.allowedCidrs An array of CIDR strings specifying allowed IP ranges for the API key. Defaults to ["0.0.0.0/0"].
 * @param {object[]?} options.scopes An array of scope objects defining the permissions for the API key. Defaults to a set of common scopes.
 * @returns {Promise<ApiContext>} A promise resolving to the created API context or throwing an error if creation failed.
 */
export async function createApiKey({
  url,
  name,
  description,
  isEnabled,
  allowedCidrs,
  scopes,
  roblosecurity,
}) {
  if (!url) url = "https://apis.roblox.com/cloud-authentication/v1/apiKey";
  const csrfToken = await getRobloxCsrfToken({ url, roblosecurity });

  const res = await fetch(url, {
    method: "POST",
    headers: {
      "x-csrf-token": csrfToken,
      "Content-Type": "application/json",
      Cookie: `.ROBLOSECURITY=${roblosecurity}`,
    },
    body: JSON.stringify({
      cloudAuthUserConfiguredProperties: {
        name: name || `lmir_${Math.random().toString(36).substring(2, 12)}`,
        description: description || "Generated by let-me-into-roblox",
        isEnabled: isEnabled || true,
        allowedCidrs: allowedCidrs || ["0.0.0.0/0"],
        scopes: scopes || [
          {
            scopeType: "asset-permissions",
            targetParts: ["*"],
            operations: ["write"],
          },
          {
            scopeType: "asset",
            targetParts: ["*"],
            operations: ["write", "read"],
          },
          {
            scopeType: "creator-store-product",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "game-pass",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "developer-product",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "group",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "user.inventory-item",
            targetParts: ["*"],
            operations: ["read"],
          },
          {
            scopeType: "universe.place.luau-execution-session",
            targetParts: ["*"],
            operations: ["write", "read"],
          },
          {
            scopeType: "memory-store.queue",
            targetParts: ["*"],
            operations: ["add", "dequeue", "discard"],
          },
          {
            scopeType: "memory-store.sorted-map",
            targetParts: ["*"],
            operations: ["write", "read"],
          },
          {
            scopeType: "memory-store",
            targetParts: ["*"],
            operations: ["flush", "get"],
          },
          {
            scopeType: "universe-messaging-service",
            targetParts: ["*"],
            operations: ["publish"],
          },
          {
            scopeType: "user.user-notification",
            targetParts: ["*"],
            operations: ["write"],
          },
          {
            scopeType: "universe.ordered-data-store.scope.entry",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "universe.secret",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "studio-evaluations",
            targetParts: ["*"],
            operations: ["create"],
          },
          {
            scopeType: "universe.subscription-product.subscription",
            targetParts: ["*"],
            operations: ["read"],
          },
          {
            scopeType: "universe",
            targetParts: ["*"],
            operations: ["write"],
          },
          {
            scopeType: "universe.place",
            targetParts: ["*"],
            operations: ["write"],
          },
          {
            scopeType: "universe-datastores.objects",
            targetParts: ["*"],
            operations: ["read", "create", "update", "delete", "list"],
          },
          {
            scopeType: "universe-datastores.versions",
            targetParts: ["*"],
            operations: ["read", "list"],
          },
          {
            scopeType: "universe-datastores.control",
            targetParts: ["*"],
            operations: ["create", "delete", "list", "snapshot"],
          },
          {
            scopeType: "universe.place.instance",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "universe-places",
            targetParts: ["*"],
            operations: ["write"],
          },
          {
            scopeType: "universe.user-restriction",
            targetParts: ["*"],
            operations: ["read", "write"],
          },
          {
            scopeType: "user.advanced",
            targetParts: ["*"],
            operations: ["read"],
          },
          {
            scopeType: "user.social",
            targetParts: ["*"],
            operations: ["read"],
          },
        ],
      },
    }),
  });
  const data = await res.json();

  if (res.status !== 200) {
    throw new Error(
      `Failed to create API key: ${res.status} ${JSON.stringify(data)}`,
    );
  }

  return {
    id: data.cloudAuthInfo.id,
    userId: data.cloudAuthInfo.ownerId,
    apiKey: data.apikeySecret,
    roblosecurity,
  };
}
